DATA:
  dataset: refcocog_u
  train_lmdb: datasets/lmdb/refcocog_u/train.lmdb
  train_split: train
  val_lmdb: datasets/lmdb/refcocog_u/val.lmdb
  val_split: val
  mask_root: datasets/masks/refcocog_u
TRAIN:
  # Base Arch
  use_openclip: True
  clip_pretrain: pretrain/ViT-H-14.pt
  input_size: 224
  word_len: 22
  text_length: 22
  word_dim: 768
  vis_dim: 768
  fpn_in: [1024, 1024, 1024, 768] # output of the transformer's intermediate patch layers.
  fpn_out: [256, 768, 768]
  sync_bn: True
  # Decoder
  num_layers: 3
  num_head: 8
  dim_ffn: 512
  dropout: 0.1
  intermediate: False
  # Training Setting
  workers: 64  # data loader workers
  workers_val: 64
  epochs: 60
  milestones: [35]
  start_epoch: 0
  batch_size: 16  # batch size for training
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.0001
  lr_decay: 0.1
  lr_multi: 0.1
  weight_decay: 0.
  max_norm: 0.
  manual_seed: 0
  print_freq: 10
  # Resume & Save
  exp_name: CRIS_VITL
  output_folder: exp/refcocog_u
  save_freq: 1
  weight: 
  resume: 
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://localhost:3681
  dist_backend: 'nccl'
  multiprocessing_distributed: False
  world_size: 1
  rank: 0
TEST:
  test_split: val-test
  test_lmdb: datasets/lmdb/refcocog_u/val.lmdb
  visualize: False
